# Notes:
#   - Minimal appveyor.yml file is an empty file. All sections are optional.
#   - Indent each level of configuration with 2 spaces. Do not use tabs!
#   - All section names are case-sensitive.
#   - Section names should be unique on each level.
 
#---------------------------------#
#      general configuration      #
#---------------------------------#
 
# version format
version: 1.0.{build}

 
#---------------------------------#
#       build configuration       #
#---------------------------------#
 
# build platform, i.e. x86, x64, Any CPU. This setting is optional.
platform: Any CPU
 
# to add several platforms to build matrix:
#platform:
#  - x86
#  - Any CPU
 
# build Configuration, i.e. Debug, Release, etc.
configuration: Release
 
# to add several configurations to build matrix:
#configuration:
#  - Debug
#  - Release
 
build:
  parallel: true                  # enable MSBuild parallel builds
  project: Source/SD.CodeProblem.DevAssignment.sln      # path to Visual Studio solution or project
  publish_wap: true               # package Web Application Projects (WAP) for Web Deploy
  publish_wap_xcopy: true         # package Web Application Projects (WAP) for XCopy deployment
  publish_azure: true             # package Azure Cloud Service projects and push to artifacts
  publish_nuget: true             # package projects with .nuspec files and push to artifacts
  publish_nuget_symbols: true     # generate and publish NuGet symbol packages
  include_nuget_references: true  # add -IncludeReferencedProjects option while packaging NuGet artifacts
 
  # MSBuild verbosity level
  verbosity: detailed
 
 
# scripts to run before build
before_build:
 
# scripts to run after build
after_build:
 
# to run your custom scripts instead of automatic MSBuild
build_script:
 
# to disable automatic builds
#build: off
 
#---------------------------------#
#       tests configuration       #
#---------------------------------#

